apiVersion: v2
name: wg-easy
description: >-
  Using the offical wg-easy/wg-easy image with almost any environment variables
  for K8s. Supporting Init Mode.
type: application
version: 1.2.0
appVersion: 15.3.0
icon: >-
  https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wg-easy/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wg-easy
    - name: Offical wg-easy Documentation
      url: https://wg-easy.github.io/wg-easy/latest/
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: added
      description: "deps: update ghcr.io/wg-easy/wg-easy docker tag to v15.4.0"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/6858a1dc682b32c982ccb5c0beb0226f16016d73
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wg-easy
      image: ghcr.io/wg-easy/wg-easy:15.4.0
keywords:
  - wireguard
  - vpn
  - wg-easy
