wordpress:
  init:
    existingSecret: "wordpress-test-secret"
    firstname: "John"
    lastname: "Doe"
    title: "John Does's Blog"
  url: "https://example.com"
mariadb:
  auth:
    database: "wordpress_db"
    username: "wordpress_db_user"
    existingSecret: "wordpress-test-secret"
