apiVersion: v2
name: wordpress
description: >-
  Using the official WordPress image. This chart provides automation for
  installation, user management, plugin installation, and metrics.
type: application
version: 5.4.3
appVersion: 7.0.1
icon: >-
  https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wordpress
    - name: Official WordPress Repository
      url: https://github.com/docker-library/
    - name: "SlyMetrics WordPress plugin for Prometheus Metrics"
      url: https://github.com/slydlake/slymetrics
    - name: Apache Metrics container
      url: https://github.com/Lusitaniae/apache_exporter
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: fixed
      description: "deps: update docker.io/memcached:1.6.45 docker digest to 0af07b2"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/4433b18ad214734c13a4ae65d23197c658fbd2ce
    - kind: fixed
      description: "deps: update docker.io/memcached:1.6.45 docker digest to 7fb608d"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/5a329a8fd90b90e9e998d98c1f4761b9b1661b70
    - kind: fixed
      description: "deps: update docker.io/redis:8.10.0-trixie docker digest to ba4c823"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/7e4d188d191be60c48379b4660f8ab7fde5a6cfd
    - kind: fixed
      description: "deps: update docker.io/wordpress:7.0.2-php8.3-apache docker digest to ef1818e"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/aabb567e5ce58d22bbb0572aaf34c257a112b88b
    - kind: fixed
      description: "deps: update mariadb docker tag to v0.16.8"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/4e9e8c9365a3684ca19342c668fa16877c3b7c9d
    - kind: fixed
      description: "deps: update memcached docker tag to v0.14.4"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/842c28cb96f4d61e327c30bdfdcd018aa902cf0d
  artifacthub.io/images: |
    - name: wordpress
      image: docker.io/wordpress:7.0.2-php8.3-apache
    - name: wordpress-cli
      image: docker.io/wordpress:cli-2.12.0-php8.3
    - name: metrics-apache
      image: docker.io/lusotycoon/apache-exporter:v1.1.1
    - name: mariadb
      image: docker.io/mariadb:12.3.2-noble
    - name: memcached
      image: docker.io/memcached:1.6.45
    - name: redis
      image: docker.io/redis:8.10.0-trixie
    - name: valkey
      image: docker.io/valkey/valkey:9.1.1-trixie
dependencies:
  - condition: memcached.enabled
    name: memcached
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.14.4
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.34.0
  - condition: valkey.enabled
    name: valkey
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.25.0
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.16.8
keywords:
  - wordpress
  - blog
