apiVersion: v2
name: wordpress
description: >-
  Using the official WordPress image. This chart provides automation for
  installation, user management, plugin installation, and metrics.
type: application
version: 5.1.30
appVersion: 7.0.1
icon: >-
  https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wordpress
    - name: Official WordPress Repository
      url: https://github.com/docker-library/
    - name: "SlyMetrics WordPress plugin for Prometheus Metrics"
      url: https://github.com/slydlake/slymetrics
    - name: Apache Metrics container
      url: https://github.com/Lusitaniae/apache_exporter
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: fixed
      description: "deps: update redis docker tag to v0.33.0"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/3f7b7a811cf39baec88c015c3122a99c9e1fb098
  artifacthub.io/images: |
    - name: wordpress
      image: docker.io/wordpress:7.0.2-php8.3-apache
    - name: wordpress-cli
      image: docker.io/wordpress:cli-2.12.0-php8.3
    - name: metrics-apache
      image: docker.io/lusotycoon/apache-exporter:v1.1.1
    - name: mariadb
      image: docker.io/mariadb:12.3.2-noble
    - name: memcached
      image: docker.io/memcached:1.6.45
    - name: redis
      image: docker.io/redis:8.8.1-trixie
    - name: valkey
      image: docker.io/valkey/valkey:9.1.1-trixie
dependencies:
  - condition: memcached.enabled
    name: memcached
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.14.2
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.33.0
  - condition: valkey.enabled
    name: valkey
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.24.4
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.16.6
keywords:
  - wordpress
  - blog
